# ---
# version: "3.8"
# services:
#   zookeeper-1:
#     image: confluentinc/cp-zookeeper:5.5.1
#     environment:
#       ZOOKEEPER_SERVER_ID: 1
#       # ZOO_SERVERS: server.1=zookeeper-1:2888:3888,server.2=zookeeper-2:2888:3888,server.3=zookeeper-3:2888:3888
#       ZOO_SERVERS: server.1=zookeeper-1:2888:3888,server.2=zookeeper-2:2889:3889,server.3=zookeeper-3:2890:3890
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 5
#       ZOOKEEPER_SYNC_LIMIT: 2
#     ports:
#       - "2181:2181" # Client port
#       - "2888:2888" # Leader election port
#       - "3888:3888" # Peer communication port

#   zookeeper-2:
#     image: confluentinc/cp-zookeeper:5.5.1
#     environment:
#       ZOOKEEPER_SERVER_ID: 2
#       # ZOO_SERVERS: server.1=zookeeper-1:2888:3888,server.2=zookeeper-2:2888:3888,server.3=zookeeper-3:2888:3888
#       ZOO_SERVERS: server.1=zookeeper-1:2888:3888,server.2=zookeeper-2:2889:3889,server.3=zookeeper-3:2890:3890
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 5
#       ZOOKEEPER_SYNC_LIMIT: 2
#     ports:
#       - "2182:2181" # Client port
#       - "2889:2888" # Leader election port
#       - "3889:3888" # Peer communication port

#   zookeeper-3:
#     image: confluentinc/cp-zookeeper:5.5.1
#     environment:
#       ZOOKEEPER_SERVER_ID: 3
#       # ZOO_SERVERS: server.1=zookeeper-1:2888:3888,server.2=zookeeper-2:2888:3888,server.3=zookeeper-3:2888:3888
#       ZOO_SERVERS: server.1=zookeeper-1:2888:3888,server.2=zookeeper-2:2889:3889,server.3=zookeeper-3:2890:3890
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 5
#       ZOOKEEPER_SYNC_LIMIT: 2
#     ports:
#       - "2183:2181" # Client port
#       - "2890:2888" # Leader election port
#       - "3890:3888" # Peer communication port

#   kafka-1:
#     image: confluentinc/cp-kafka:5.5.1
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181

#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://43.201.244.153:9092
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#       KAFKA_NUM_PARTITIONS: 3

#   kafka-2:
#     image: confluentinc/cp-kafka:5.5.1
#     ports:
#       - "9093:9093"
#     environment:
#       KAFKA_BROKER_ID: 2
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181

#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://43.201.244.153:9093
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#       KAFKA_NUM_PARTITIONS: 3

#   kafka-3:
#     image: confluentinc/cp-kafka:5.5.1
#     ports:
#       - "9094:9094"
#     environment:
#       KAFKA_BROKER_ID: 3
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181

#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29094,EXTERNAL://43.201.244.153:9094
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#       KAFKA_NUM_PARTITIONS: 3

version: "3.0"
services:
  zk1:
    image: zookeeper
    restart: always
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - "~/zk-cluster/zk1/data:/data"

  zk2:
    image: zookeeper
    restart: always
    hostname: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - "~/zk-cluster/zk2/data:/data"

  zk3:
    image: zookeeper
    restart: always
    hostname: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - "~/zk-cluster/zk3/data:/data"

  zoo-navi:
    image: elkozmon/zoonavigator
    ports:
      - 9000:9000
    environment:
      HTTP_PORT: 9000

  kafka1:
    image: confluentinc/cp-kafka
    depends_on:
      - zk1
      - zk2
      - zk3
    restart: on-failure
    ports:
      - 9091:9091
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://호스트IP:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093

  kafka2:
    image: confluentinc/cp-kafka
    depends_on:
      - zk1
      - zk2
      - zk3
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://호스트IP:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093

  kafka3:
    image: confluentinc/cp-kafka
    depends_on:
      - zk1
      - zk2
      - zk3
    restart: on-failure
    ports:
      - 9093:9093
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://호스트IP:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_BROKER_ID=3
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
